version: "3"
services:
  api:
    image: kasibhub/backend-prod:$NEW_VERSION 
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=$SECRET_KEY
      - DEBUG=$DEBUG
      - API_KEY=$API_KEY
    depends_on:
      - db
  nginx:
    image: kasibhub/webserver-prod:$NEW_VERSION
    restart: always
    ports:
      - "80:80"
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  postgres_data: